
source("LoadData.R")
png(filename = "Plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
plot(Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)", xaxt = "n")
axis(side = 1, at = seq(1,2880, by = 1439), labels = c("Thu", "Fri", "Sat"))
plot(Voltage, type = "l", xlab = "datetime", xaxt = "n", ylab = "Voltage")
axis(side = 1, at = seq(1,2880, by = 1439), labels = c("Thu", "Fri", "Sat"))
plot(Sub_metering_1, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)", xaxt = "n")
lines(Sub_metering_2, col = "red")
lines(Sub_metering_3, col = "blue")
legend("topright", bty = "n", col = c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd = 1)
axis(side = 1, at = seq(1,2880, by = 1439), labels = c("Thu", "Fri", "Sat"))
plot(Global_reactive_power, type = "l", xlab = "datetime", xaxt = "n")
axis(side = 1, at = seq(1,2880, by = 1439), labels = c("Thu", "Fri", "Sat"))
dev.off()
rm(epc)
